### PR TITLE
Better handling of negative cellSpacing

### PR DESCRIPTION
**Pull request by tomasandrle**
Avoid glitching when cellSpacing is set to a negative value.

### CODE REVIEW

**Comment by MaherKSantina** [comment]
Thanks @tomasandrle for raising this PR! 🙏 What do you think about removing negative spacing support all together (Instead of having a Bool to specify that). Will there be a case where we need negative spacing?

**Comment by tomasandrle** [comment]
I needed this to fix my layout. I applied a scale transform to cells going out of view (to make them look smaller) and setting negative spacing helped me achieve the desired layout.

I'm not sure about the elegance of my fix (bool) but I definitely need it - it's not a theoretical thing, if you know what I mean.

I totally understand that this is an edge case in a general purpose library.

**Comment by MaherKSantina** [comment]
Ohh thanks for the detailed explanation! If that's the case then I'm happy with the fix
Great Job 👍

**Review by MaherKSantina — APPROVED** [review]

**Review by MaherKSantina — CHANGES_REQUESTED** [review]
Sorry @tomasandrle I just tried to build it for the example app in the project and it looks like it breaks the current implementation. What do you think we make it backward compatible by specifying a default value to the `m` variable?
And also, do you think we can change the variable `m` to something more expressive? Like `allowNegativeValues: Bool` ? Sorry about that 😢

**Comment by tomasandrle** [comment]
You're right, that was lazy of me. I'll re-test and improve the patch.

**Review by MaherKSantina — APPROVED** [review]
Amazing 👍

**Pull request merged**
