### PR TITLE
Add minimumItemsToScroll functionality

### PR DESCRIPTION
**Pull request by omastny**
I needed the ability to enter a minimumItemsToScroll, if multiple item are displayed simultaneously. So it is more paging like.

### CODE REVIEW

**Comment by MaherKSantina** [comment]
@omastny That's a great idea! 
Thank you so much for the contribution much appreciated! 🎉 I'm going to add some tests for that and bump the version number and create a release!

Cheers!

**Comment by MaherKSantina** [comment]
@omastny the change was merged in! you can install pod version 1.3.0 to get the new update. Again thanks for the contribution! 🎖

**Comment by omastny** [comment]
@MaherKSantina No problem. Thank you for this repo. Saved me a lot of time 👍

**Comment by MaherKSantina** [comment]
@omastny glad to hear that mate! 👍

**Pull request merged**
