### PR TITLE
Updated for Swift 4.2

### PR DESCRIPTION
**Pull request by digitaljerry**

### CODE REVIEW

**Comment by MaherKSantina** [comment]
Much appreciated @digitaljerry 🥇 ! I'll test this when I get back home and merge it

**Comment by Luccifer** [comment]
@MaherKSantina any news?

**Comment by MaherKSantina** [comment]
@Luccifer I'm on my way home give me an hour and I'll test it out. I need to also fix the failing tests. Thank you for the message!

**Comment by MaherKSantina** [comment]
@digitaljerry I need to do some changes on this PR to make it work is it okay to push my changes to your branch?

**Comment by digitaljerry** [comment]
@MaherKSantina sure. Go ahead.
Btw, I did this to make it compatible with XCode 10.2 which no longer supports Swift 3.x.

**Comment by MaherKSantina** [comment]
@digitaljerry yeah I figured, I should have upgraded this pod long ago. I'll do it now and make a release. Thank you so much for the contribution!

**Comment by MaherKSantina** [comment]
@digitaljerry version 1.2.0 is live with swift 4.2 included!

**Comment by digitaljerry** [comment]
Awesome. Thanks @MaherKSantina for a fast release. Deleting my fork.

**Comment by MaherKSantina** [comment]
@digitaljerry no worries mate! Have a good day!

**Pull request merged**
